/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Library3RuntimeModule extends at.ac.tuwien.big.xmltext.library3.AbstractLibrary3RuntimeModule {

}
