/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class Library3StandaloneSetup extends Library3StandaloneSetupGenerated{

	public static void doSetup() {
		new Library3StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

