/*
 * generated by Xtext
 */
package at.ac.tuwien.big.servicelang.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.ac.tuwien.big.servicelang.services.ServiceGrammarAccess;

public class ServiceParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ServiceGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.ac.tuwien.big.servicelang.parser.antlr.internal.InternalServiceParser createParser(XtextTokenStream stream) {
		return new at.ac.tuwien.big.servicelang.parser.antlr.internal.InternalServiceParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Container";
	}
	
	public ServiceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ServiceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
