/*
* generated by Xtext
*/
package eu.artist.tosca.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.artist.tosca.dsl.services.ToscaDSLGrammarAccess;

public class ToscaDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ToscaDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected eu.artist.tosca.dsl.parser.antlr.internal.InternalToscaDSLParser createParser(XtextTokenStream stream) {
		return new eu.artist.tosca.dsl.parser.antlr.internal.InternalToscaDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DocumentRoot";
	}
	
	public ToscaDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ToscaDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
