/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import at.ac.tuwien.big.xmltext.library3.services.Library3GrammarAccess;

public class Library3Parser extends AbstractContentAssistParser {
	
	@Inject
	private Library3GrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected at.ac.tuwien.big.xmltext.library3.ui.contentassist.antlr.internal.InternalLibrary3Parser createParser() {
		at.ac.tuwien.big.xmltext.library3.ui.contentassist.antlr.internal.InternalLibrary3Parser result = new at.ac.tuwien.big.xmltext.library3.ui.contentassist.antlr.internal.InternalLibrary3Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAnyGenericConstructAccess().getAlternatives(), "rule__AnyGenericConstruct__Alternatives");
					put(grammarAccess.getLibraryTypeAccess().getGroup(), "rule__LibraryType__Group__0");
					put(grammarAccess.getLibraryTypeAccess().getGroup_3(), "rule__LibraryType__Group_3__0");
					put(grammarAccess.getLibraryTypeAccess().getGroup_3_1(), "rule__LibraryType__Group_3_1__0");
					put(grammarAccess.getLibraryTypeAccess().getGroup_4(), "rule__LibraryType__Group_4__0");
					put(grammarAccess.getLibraryTypeAccess().getGroup_4_1(), "rule__LibraryType__Group_4_1__0");
					put(grammarAccess.getBookTypeAccess().getGroup(), "rule__BookType__Group__0");
					put(grammarAccess.getCustomerTypeAccess().getGroup(), "rule__CustomerType__Group__0");
					put(grammarAccess.getCustomerTypeAccess().getGroup_6(), "rule__CustomerType__Group_6__0");
					put(grammarAccess.getBookInfoTypeAccess().getGroup(), "rule__BookInfoType__Group__0");
					put(grammarAccess.getBookInfoTypeAccess().getGroup_2(), "rule__BookInfoType__Group_2__0");
					put(grammarAccess.getBookInfoTypeAccess().getGroup_2_1(), "rule__BookInfoType__Group_2_1__0");
					put(grammarAccess.getAnyGenericElementAccess().getGroup(), "rule__AnyGenericElement__Group__0");
					put(grammarAccess.getAnyGenericElementAccess().getGroup_3(), "rule__AnyGenericElement__Group_3__0");
					put(grammarAccess.getAnyGenericElementAccess().getGroup_4(), "rule__AnyGenericElement__Group_4__0");
					put(grammarAccess.getAnyGenericElementAccess().getGroup_4_1(), "rule__AnyGenericElement__Group_4_1__0");
					put(grammarAccess.getAnyGenericElementAccess().getGroup_5(), "rule__AnyGenericElement__Group_5__0");
					put(grammarAccess.getAnyGenericElementAccess().getGroup_5_1(), "rule__AnyGenericElement__Group_5_1__0");
					put(grammarAccess.getAnyGenericAttributeAccess().getGroup(), "rule__AnyGenericAttribute__Group__0");
					put(grammarAccess.getAnyGenericTextAccess().getGroup(), "rule__AnyGenericText__Group__0");
					put(grammarAccess.getLibraryTypeAccess().getBookAssignment_3_0(), "rule__LibraryType__BookAssignment_3_0");
					put(grammarAccess.getLibraryTypeAccess().getBookAssignment_3_1_1(), "rule__LibraryType__BookAssignment_3_1_1");
					put(grammarAccess.getLibraryTypeAccess().getCustomerAssignment_4_0(), "rule__LibraryType__CustomerAssignment_4_0");
					put(grammarAccess.getLibraryTypeAccess().getCustomerAssignment_4_1_1(), "rule__LibraryType__CustomerAssignment_4_1_1");
					put(grammarAccess.getBookTypeAccess().getNameAssignment_1(), "rule__BookType__NameAssignment_1");
					put(grammarAccess.getBookTypeAccess().getTitleAssignment_4(), "rule__BookType__TitleAssignment_4");
					put(grammarAccess.getBookTypeAccess().getAuthorAssignment_6(), "rule__BookType__AuthorAssignment_6");
					put(grammarAccess.getBookTypeAccess().getPagesAssignment_8(), "rule__BookType__PagesAssignment_8");
					put(grammarAccess.getBookTypeAccess().getIsbnAssignment_10(), "rule__BookType__IsbnAssignment_10");
					put(grammarAccess.getBookTypeAccess().getBookInfoAssignment_11(), "rule__BookType__BookInfoAssignment_11");
					put(grammarAccess.getCustomerTypeAccess().getFirstNameAssignment_3(), "rule__CustomerType__FirstNameAssignment_3");
					put(grammarAccess.getCustomerTypeAccess().getLastNameAssignment_5(), "rule__CustomerType__LastNameAssignment_5");
					put(grammarAccess.getCustomerTypeAccess().getBorrowedBookIdAssignment_6_1(), "rule__CustomerType__BorrowedBookIdAssignment_6_1");
					put(grammarAccess.getBookInfoTypeAccess().getAnyAssignment_2_0(), "rule__BookInfoType__AnyAssignment_2_0");
					put(grammarAccess.getBookInfoTypeAccess().getAnyAssignment_2_1_1(), "rule__BookInfoType__AnyAssignment_2_1_1");
					put(grammarAccess.getAnyGenericElementAccess().getElemNameAssignment_2(), "rule__AnyGenericElement__ElemNameAssignment_2");
					put(grammarAccess.getAnyGenericElementAccess().getElemValueAssignment_3_1(), "rule__AnyGenericElement__ElemValueAssignment_3_1");
					put(grammarAccess.getAnyGenericElementAccess().getAnyGenericAttrAssignment_4_0(), "rule__AnyGenericElement__AnyGenericAttrAssignment_4_0");
					put(grammarAccess.getAnyGenericElementAccess().getAnyGenericAttrAssignment_4_1_1(), "rule__AnyGenericElement__AnyGenericAttrAssignment_4_1_1");
					put(grammarAccess.getAnyGenericElementAccess().getAnyGenericElementAssignment_5_0(), "rule__AnyGenericElement__AnyGenericElementAssignment_5_0");
					put(grammarAccess.getAnyGenericElementAccess().getAnyGenericElementAssignment_5_1_1(), "rule__AnyGenericElement__AnyGenericElementAssignment_5_1_1");
					put(grammarAccess.getAnyGenericAttributeAccess().getAttrNameAssignment_0(), "rule__AnyGenericAttribute__AttrNameAssignment_0");
					put(grammarAccess.getAnyGenericAttributeAccess().getAttrValueAssignment_2(), "rule__AnyGenericAttribute__AttrValueAssignment_2");
					put(grammarAccess.getAnyGenericTextAccess().getTextValueAssignment_1(), "rule__AnyGenericText__TextValueAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			at.ac.tuwien.big.xmltext.library3.ui.contentassist.antlr.internal.InternalLibrary3Parser typedParser = (at.ac.tuwien.big.xmltext.library3.ui.contentassist.antlr.internal.InternalLibrary3Parser) parser;
			typedParser.entryRuleLibraryType();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public Library3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Library3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
