/*
* generated by Xtext
*/
package at.ac.tuwien.big.amltext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.ac.tuwien.big.amltext.services.AMLTextGrammarAccess;

public class AMLTextParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AMLTextGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.ac.tuwien.big.amltext.parser.antlr.internal.InternalAMLTextParser createParser(XtextTokenStream stream) {
		return new at.ac.tuwien.big.amltext.parser.antlr.internal.InternalAMLTextParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CAEXFile";
	}
	
	public AMLTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AMLTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
