/*
 * generated by Xtext
 */
package at.ac.tuwien.big.servicelang.ui.contentassist

import at.ac.tuwien.big.servicelang.ui.contentassist.AbstractServiceProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ServiceProposalProvider extends AbstractServiceProposalProvider {
}
