/*
 * generated by Xtext
 */
package eu.artist.tosca.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ToscaDSLRuntimeModule extends eu.artist.tosca.dsl.AbstractToscaDSLRuntimeModule {

}
