/*
* generated by Xtext
*/
package eu.artist.tosca.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ToscaDSLStandaloneSetup extends ToscaDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new ToscaDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

