/*
 * generated by Xtext
 */
package at.ac.tuwien.big.servicelang;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ServiceUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return at.ac.tuwien.big.servicelang.ui.internal.ServiceActivator.getInstance().getInjector("at.ac.tuwien.big.servicelang.Service");
	}
	
}
