/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.ui.outline;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
public class Library3OutlineTreeProvider /* implements org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider  */{
}
