<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org_sl_planet_bgfSimplified" nsURI="file:/C:/Users/Robert/Documents/AME/xmltext/XMLIntellEdit/source/at.ac.tuwien.big.xmltext/bgf/bgf.xsdsimplified"
    nsPrefix="bgfs">
  <eClassifiers xsi:type="ecore:EClass" name="Allof">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="1"
        upperBound="-1" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Any"/>
  <eClassifiers xsi:type="ecore:EClass" name="Choice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="1"
        upperBound="-1" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Empty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Epsilon"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonterminal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="epsilon" eType="#//Epsilon"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="empty" eType="#//Empty"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="any" eType="#//Any" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectable" eType="#//Selectable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marked" eType="#//Marked"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" eType="#//Sequence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="choice" eType="#//Choice"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allof" eType="#//Allof"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="not" eType="#//Not" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optional" eType="#//Optional"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plus" eType="#//Plus" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="star" eType="#//Star" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seplistplus" eType="#//Seplistplus"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sepliststar" eType="#//Sepliststar"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Grammar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roots" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productions" upperBound="-1"
        eType="#//Production" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Marked">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Optional">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Production">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonterminal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Selectable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selector" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Seplistplus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression1" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sepliststar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression1" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="1"
        upperBound="-1" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Star">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Value">
    <eLiterals name="int" literal="int"/>
    <eLiterals name="string" value="1" literal="string"/>
  </eClassifiers>
</ecore:EPackage>
