/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class Library3ProposalProvider /* implements AbstractLibrary3ProposalProvider  */{
}
