/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.ac.tuwien.big.xmltext.library3.services.Library3GrammarAccess;

public class Library3Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Library3GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.ac.tuwien.big.xmltext.library3.parser.antlr.internal.InternalLibrary3Parser createParser(XtextTokenStream stream) {
		return new at.ac.tuwien.big.xmltext.library3.parser.antlr.internal.InternalLibrary3Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "LibraryType";
	}
	
	public Library3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Library3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
