/*
 * generated by Xtext
 */
package at.ac.tuwien.big.amltext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AMLTextUiModule extends at.ac.tuwien.big.amltext.ui.AbstractAMLTextUiModule {
	public AMLTextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
