/*
 * generated by Xtext
 */
package at.ac.tuwien.big.amltext.ui.contentassist

import at.ac.tuwien.big.amltext.ui.contentassist.AbstractAMLTextProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AMLTextProposalProvider extends AbstractAMLTextProposalProvider {
}
