/*
 * generated by Xtext
 */
package at.ac.tuwien.big.amltext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AMLTextRuntimeModule extends at.ac.tuwien.big.amltext.AbstractAMLTextRuntimeModule {

}
