/*
* generated by Xtext
*/
package at.ac.tuwien.big.amltext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AMLTextStandaloneSetup extends AMLTextStandaloneSetupGenerated{

	public static void doSetup() {
		new AMLTextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

