/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Library3UiModule extends at.ac.tuwien.big.xmltext.library3.ui.AbstractLibrary3UiModule {
	public Library3UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
