/*
 * generated by Xtext
 */
package eu.artist.tosca.dsl.ui.contentassist

import eu.artist.tosca.dsl.ui.contentassist.AbstractToscaDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ToscaDSLProposalProvider extends AbstractToscaDSLProposalProvider {
}
