/*
 * generated by Xtext
 */
package at.ac.tuwien.big.servicelang.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

import at.ac.tuwien.big.xmlintelledit.intelledit.xtext.DynamicValidator;

public class AbstractServiceValidator extends DynamicValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/serviceexample"));
		return result;
	}
}
