/*
* generated by Xtext
*/
package eu.artist.tosca.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ToscaDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return eu.artist.tosca.dsl.ui.internal.ToscaDSLActivator.getInstance().getInjector("eu.artist.tosca.dsl.ToscaDSL");
	}
	
}
