/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.ui.contentassist

import at.ac.tuwien.big.xmltext.library3.ui.contentassist.AbstractLibrary3ProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class Library3ProposalProvider extends AbstractLibrary3ProposalProvider {
}
