/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.ac.tuwien.big.xmltext.library3.ui.internal.Library3Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Library3ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Library3Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Library3Activator.getInstance().getInjector(Library3Activator.AT_AC_TUWIEN_BIG_XMLTEXT_LIBRARY3_LIBRARY3);
	}
	
}
