/*
 * generated by Xtext
 */
package eu.artist.tosca.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ToscaDSLUiModule extends eu.artist.tosca.dsl.ui.AbstractToscaDSLUiModule {
	public ToscaDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
