/*
* generated by Xtext
*/
package at.ac.tuwien.big.amltext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AMLTextUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.ac.tuwien.big.amltext.ui.internal.AMLTextActivator.getInstance().getInjector("at.ac.tuwien.big.amltext.AMLText");
	}
	
}
