/**
 */
package org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.util.org_eclipse_smarthome_schemas_thing_description_v1__0SimplifiedAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class org_eclipse_smarthome_schemas_thing_description_v1__0SimplifiedItemProviderAdapterFactory extends org_eclipse_smarthome_schemas_thing_description_v1__0SimplifiedAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public org_eclipse_smarthome_schemas_thing_description_v1__0SimplifiedItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.BridgeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BridgeTypeItemProvider bridgeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.BridgeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBridgeTypeAdapter() {
		if (bridgeTypeItemProvider == null) {
			bridgeTypeItemProvider = new BridgeTypeItemProvider(this);
		}

		return bridgeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.BridgeTypeRef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BridgeTypeRefItemProvider bridgeTypeRefItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.BridgeTypeRef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBridgeTypeRefAdapter() {
		if (bridgeTypeRefItemProvider == null) {
			bridgeTypeRefItemProvider = new BridgeTypeRefItemProvider(this);
		}

		return bridgeTypeRefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Channel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChannelItemProvider channelItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Channel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChannelAdapter() {
		if (channelItemProvider == null) {
			channelItemProvider = new ChannelItemProvider(this);
		}

		return channelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ChannelGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChannelGroupItemProvider channelGroupItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ChannelGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChannelGroupAdapter() {
		if (channelGroupItemProvider == null) {
			channelGroupItemProvider = new ChannelGroupItemProvider(this);
		}

		return channelGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ChannelGroups} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChannelGroupsItemProvider channelGroupsItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ChannelGroups}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChannelGroupsAdapter() {
		if (channelGroupsItemProvider == null) {
			channelGroupsItemProvider = new ChannelGroupsItemProvider(this);
		}

		return channelGroupsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ChannelGroupType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChannelGroupTypeItemProvider channelGroupTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ChannelGroupType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChannelGroupTypeAdapter() {
		if (channelGroupTypeItemProvider == null) {
			channelGroupTypeItemProvider = new ChannelGroupTypeItemProvider(this);
		}

		return channelGroupTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Channels} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChannelsItemProvider channelsItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Channels}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChannelsAdapter() {
		if (channelsItemProvider == null) {
			channelsItemProvider = new ChannelsItemProvider(this);
		}

		return channelsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ChannelType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChannelTypeItemProvider channelTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ChannelType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChannelTypeAdapter() {
		if (channelTypeItemProvider == null) {
			channelTypeItemProvider = new ChannelTypeItemProvider(this);
		}

		return channelTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ConfigDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigDescriptionItemProvider configDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ConfigDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigDescriptionAdapter() {
		if (configDescriptionItemProvider == null) {
			configDescriptionItemProvider = new ConfigDescriptionItemProvider(this);
		}

		return configDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ConfigDescriptionRef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigDescriptionRefItemProvider configDescriptionRefItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ConfigDescriptionRef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigDescriptionRefAdapter() {
		if (configDescriptionRefItemProvider == null) {
			configDescriptionRefItemProvider = new ConfigDescriptionRefItemProvider(this);
		}

		return configDescriptionRefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ConfigDescriptionsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigDescriptionsTypeItemProvider configDescriptionsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ConfigDescriptionsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigDescriptionsTypeAdapter() {
		if (configDescriptionsTypeItemProvider == null) {
			configDescriptionsTypeItemProvider = new ConfigDescriptionsTypeItemProvider(this);
		}

		return configDescriptionsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.CriteriaType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CriteriaTypeItemProvider criteriaTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.CriteriaType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCriteriaTypeAdapter() {
		if (criteriaTypeItemProvider == null) {
			criteriaTypeItemProvider = new CriteriaTypeItemProvider(this);
		}

		return criteriaTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Event} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EventItemProvider eventItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Event}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEventAdapter() {
		if (eventItemProvider == null) {
			eventItemProvider = new EventItemProvider(this);
		}

		return eventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.FilterType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FilterTypeItemProvider filterTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.FilterType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFilterTypeAdapter() {
		if (filterTypeItemProvider == null) {
			filterTypeItemProvider = new FilterTypeItemProvider(this);
		}

		return filterTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Option} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OptionItemProvider optionItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Option}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOptionAdapter() {
		if (optionItemProvider == null) {
			optionItemProvider = new OptionItemProvider(this);
		}

		return optionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Options} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OptionsItemProvider optionsItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Options}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOptionsAdapter() {
		if (optionsItemProvider == null) {
			optionsItemProvider = new OptionsItemProvider(this);
		}

		return optionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.OptionsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OptionsTypeItemProvider optionsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.OptionsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOptionsTypeAdapter() {
		if (optionsTypeItemProvider == null) {
			optionsTypeItemProvider = new OptionsTypeItemProvider(this);
		}

		return optionsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.OptionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OptionTypeItemProvider optionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.OptionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOptionTypeAdapter() {
		if (optionTypeItemProvider == null) {
			optionTypeItemProvider = new OptionTypeItemProvider(this);
		}

		return optionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ParameterGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterGroupItemProvider parameterGroupItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ParameterGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterGroupAdapter() {
		if (parameterGroupItemProvider == null) {
			parameterGroupItemProvider = new ParameterGroupItemProvider(this);
		}

		return parameterGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Properties} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertiesItemProvider propertiesItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Properties}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertiesAdapter() {
		if (propertiesItemProvider == null) {
			propertiesItemProvider = new PropertiesItemProvider(this);
		}

		return propertiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Property} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyItemProvider propertyItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Property}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyAdapter() {
		if (propertyItemProvider == null) {
			propertyItemProvider = new PropertyItemProvider(this);
		}

		return propertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.State} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateItemProvider stateItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.State}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateAdapter() {
		if (stateItemProvider == null) {
			stateItemProvider = new StateItemProvider(this);
		}

		return stateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.SupportedBridgeTypeRefs} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SupportedBridgeTypeRefsItemProvider supportedBridgeTypeRefsItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.SupportedBridgeTypeRefs}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSupportedBridgeTypeRefsAdapter() {
		if (supportedBridgeTypeRefsItemProvider == null) {
			supportedBridgeTypeRefsItemProvider = new SupportedBridgeTypeRefsItemProvider(this);
		}

		return supportedBridgeTypeRefsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Tags} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TagsItemProvider tagsItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.Tags}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTagsAdapter() {
		if (tagsItemProvider == null) {
			tagsItemProvider = new TagsItemProvider(this);
		}

		return tagsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ThingDescriptionsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThingDescriptionsTypeItemProvider thingDescriptionsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ThingDescriptionsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThingDescriptionsTypeAdapter() {
		if (thingDescriptionsTypeItemProvider == null) {
			thingDescriptionsTypeItemProvider = new ThingDescriptionsTypeItemProvider(this);
		}

		return thingDescriptionsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ThingType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThingTypeItemProvider thingTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org_eclipse_smarthome_schemas_thing_description_v1__0Simplified.ThingType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThingTypeAdapter() {
		if (thingTypeItemProvider == null) {
			thingTypeItemProvider = new ThingTypeItemProvider(this);
		}

		return thingTypeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (bridgeTypeItemProvider != null) bridgeTypeItemProvider.dispose();
		if (bridgeTypeRefItemProvider != null) bridgeTypeRefItemProvider.dispose();
		if (channelItemProvider != null) channelItemProvider.dispose();
		if (channelGroupItemProvider != null) channelGroupItemProvider.dispose();
		if (channelGroupsItemProvider != null) channelGroupsItemProvider.dispose();
		if (channelGroupTypeItemProvider != null) channelGroupTypeItemProvider.dispose();
		if (channelsItemProvider != null) channelsItemProvider.dispose();
		if (channelTypeItemProvider != null) channelTypeItemProvider.dispose();
		if (configDescriptionItemProvider != null) configDescriptionItemProvider.dispose();
		if (configDescriptionRefItemProvider != null) configDescriptionRefItemProvider.dispose();
		if (configDescriptionsTypeItemProvider != null) configDescriptionsTypeItemProvider.dispose();
		if (criteriaTypeItemProvider != null) criteriaTypeItemProvider.dispose();
		if (eventItemProvider != null) eventItemProvider.dispose();
		if (filterTypeItemProvider != null) filterTypeItemProvider.dispose();
		if (optionItemProvider != null) optionItemProvider.dispose();
		if (optionsItemProvider != null) optionsItemProvider.dispose();
		if (optionsTypeItemProvider != null) optionsTypeItemProvider.dispose();
		if (optionTypeItemProvider != null) optionTypeItemProvider.dispose();
		if (parameterItemProvider != null) parameterItemProvider.dispose();
		if (parameterGroupItemProvider != null) parameterGroupItemProvider.dispose();
		if (propertiesItemProvider != null) propertiesItemProvider.dispose();
		if (propertyItemProvider != null) propertyItemProvider.dispose();
		if (stateItemProvider != null) stateItemProvider.dispose();
		if (supportedBridgeTypeRefsItemProvider != null) supportedBridgeTypeRefsItemProvider.dispose();
		if (tagsItemProvider != null) tagsItemProvider.dispose();
		if (thingDescriptionsTypeItemProvider != null) thingDescriptionsTypeItemProvider.dispose();
		if (thingTypeItemProvider != null) thingTypeItemProvider.dispose();
	}

}
