/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.ui.labeling;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
public class Library3LabelProvider /* implements org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider  */{
  /* @Inject
   */public Library3LabelProvider(final /* org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider */Object delegate) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AdapterFactoryLabelProvider) is undefined");
  }
}
