/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.ui.labeling;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
public class Library3DescriptionLabelProvider /* implements org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider  */{
}
