/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.ui.quickfix;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
public class Library3QuickfixProvider /* implements org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider  */{
}
